name: Changelog CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read VERSION
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Update changelog with version and commit message
        if: github.event_name == 'push'
        run: |
          VERSION=$(cat VERSION)
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "- $VERSION $COMMIT_MSG" >> CHANGELOG.md

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.2.0
        with:
          release_version: ${{ steps.read_version.outputs.VERSION }}
